// Regenerate js/dragon-glb.js from assets/dragon.glb (embeds the model as base64
// so the game works from file:// where fetch/XHR is blocked).
const fs = require('fs');
const glb = fs.readFileSync('assets/dragon.glb');
const out = '// GENERATED by tools/build-glb-b64.js — do not edit\n' +
  'const DRAGON_GLB_B64 = "' + glb.toString('base64') + '";\n';
fs.writeFileSync('js/dragon-glb.js', out);
console.log('wrote js/dragon-glb.js', Math.round(out.length / 1024) + ' KB');
