// Regenerate the embedded-model JS files (base64, so the game works from
// file:// where fetch/XHR is blocked):
//   assets/dragon.glb  -> js/dragon-glb.js  (DRAGON_GLB_B64)
//   assets/caravel.glb -> js/ship-glb.js    (SHIP_GLB_B64)
const fs = require('fs');
const emit = (src, dest, constName) => {
  const glb = fs.readFileSync(src);
  const out = '// GENERATED by tools/build-glb-b64.js — do not edit\n' +
    'const ' + constName + ' = "' + glb.toString('base64') + '";\n';
  fs.writeFileSync(dest, out);
  console.log('wrote', dest, Math.round(out.length / 1024) + ' KB');
};
emit('assets/dragon.glb', 'js/dragon-glb.js', 'DRAGON_GLB_B64');
emit('assets/caravel.glb', 'js/ship-glb.js', 'SHIP_GLB_B64');
