// Regenerate the embedded-model JS files — embeds the models as base64
// so the game works from file:// (fetch/XHR blocked there).
const fs = require('fs');
const b64 = p => fs.readFileSync(p).toString('base64');
const out = '// GENERATED by tools/build-glb-b64.js — do not edit\n' +
  'const DRAGON_GLB_DEMON = "' + b64('assets/dragon_demon.glb') + '";\n' +
  'const DRAGON_GLB_RED   = "' + b64('assets/dragon_red.glb') + '";\n' +
  'const DRAGON_GLB_GOLD  = "' + b64('assets/dragon_gold.glb') + '";\n';
fs.writeFileSync('js/dragon-glb.js', out);
console.log('wrote js/dragon-glb.js', Math.round(out.length / 1024) + ' KB');
const ship = '// GENERATED by tools/build-glb-b64.js — do not edit\n' +
  'const SHIP_GLB_B64 = "' + b64('assets/caravel.glb') + '";\n';
fs.writeFileSync('js/ship-glb.js', ship);
console.log('wrote js/ship-glb.js', Math.round(ship.length / 1024) + ' KB');
